### ISSUE TITLE
相似度

### ISSUE THREAD

**Issue by sakeven** [ZJGSU-Open-Source/RunServer#9]
TODO：应该检测sid小的

**Comment by JinweiClarkChao** [comment]
Tools:
**Main Page**:[The software and text similarity tester SIM](http://www.dickgrune.com/Programs/similarity_tester/)

**User Manual**: [sim.pdf](http://www.dickgrune.com/Programs/similarity_tester/sim.pdf)

I cannot fix the bug right now.

**Comment by JinweiClarkChao** [comment]
The code hustoj used for sim test: https://github.com/zhblue/hustoj/blob/master/trunk%2Fcore%2Fjudge_client%2Fjudge_client.cc#L1913

The code we used for sim test currently:
https://github.com/ZJGSU-Open-Source/RunServer/blob/master/judge.go#L138

**Comment by JinweiClarkChao** [comment]
相似度检测本身已经没有问题了。至于“检测sid小的”，这个和那个工具有关，我再考虑一下

**Comment by JinweiClarkChao** [comment]
fixed
